---

- hosts: cluster
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: raspberrypi

- hosts: master
  roles:
    - role: k3s/master
    - role: tools

- hosts: node
  roles:
    - role: k3s/node
