---
- hosts: cluster
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: raspberrypi

- hosts: master
  roles:
    - role: tools
    - role: k3s/master

- hosts: node
  roles:
    - role: k3s/node
