- name: Check if k3s service is configured
  stat:
    path: "/etc/systemd/system/k3s.service"
  register: master_svc

- name: Install k3s master
  shell: |
    export INSTALL_K3S_VERSION={{ k3s_version }}
    export K3S_KUBECONFIG_MODE="0644"
    curl -sfL https://get.k3s.io | sh -
  when: not master_svc.stat.exists

- name: Wait for node-token
  wait_for:
    path: /var/lib/rancher/k3s/server/token
  become: yes

- name: Read node-token from master
  slurp:
    path: /var/lib/rancher/k3s/server/token
  become: yes
  register: node_token

- name: Store Master node-token
  set_fact:
    token: "{{ node_token.content | b64decode | regex_replace('\n', '') }}"

# - debug:
#     var: hostvars[groups["master"][0]].token

- name: Create directory .kube
  file:
    path: ~{{ ansible_user }}/.kube
    state: directory
    owner: "{{ ansible_user }}"
    mode: "u=rwx,g=rx,o="

- name: Copy config file to user home directory
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ~{{ ansible_user }}/.kube/config
    remote_src: yes
    owner: "{{ ansible_user }}"
    mode: "u=rw,g=,o="

- name: Replace https://localhost:6443 by https://master-ip:6443
  command: >-
    k3s kubectl config set-cluster default
      --server=https://{{ master_ip }}:6443
      --kubeconfig ~{{ ansible_user }}/.kube/config
  changed_when: true
