---
- name: Enable IPv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: yes

- name: Disable IPv6 completely
  sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: "1"
    state: present
    reload: yes

- name: Disable IPv6 default
  sysctl:
    name: net.ipv6.conf.default.disable_ipv6
    value: "1"
    state: present
    reload: yes

- name: Disable IPv6 lo
  sysctl:
    name: net.ipv6.conf.lo.disable_ipv6
    value: "1"
    state: present
    reload: yes

# adjust fs.inotify for fluent_bit
- name: Adjust fs.inotify.max_user_watches
  sysctl:
    name: fs.inotify.max_user_watches
    value: "1048576"
    state: present
    reload: yes

- name: Adjust fs.inotify.max_user_instances
  sysctl:
    name: fs.inotify.max_user_instsances
    value: "512"
    state: present
    reload: yes

- name: Adjust fs.inotify.max_queued_events
  sysctl:
    name: fs.inotify.max_queued_events
    value: "16384"
    state: present
    reload: yes
