---
- name: Enable IPv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: yes

- name: Disable IPv6 completely
  sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: "1"
    state: present
    reload: yes

- name: Disable IPv6 default
  sysctl:
    name: net.ipv6.conf.default.disable_ipv6
    value: "1"
    state: present
    reload: yes

- name: Disable IPv6 lo
  sysctl:
    name: net.ipv6.conf.lo.disable_ipv6
    value: "1"
    state: present
    reload: yes
