- name: Install utility packages
  apt:
    update_cache: yes
    pkg:
      - bind9-dnsutils
      - curl
      - grep
      - iperf3
      - jq
      - net-tools
      - peco
      - screen
      - wget
      - zsh
  become: yes

# will be used to download binaries from github releases
- set_fact:
    download_arch: >-
      {{
        {
          'x86_64': 'amd64',
          'aarch64': 'arm64',
          'armv7l': 'armv7',
          'i386': '386',
          'i686': '386'
        }[ansible_architecture]
      }}

- name: Download k9s binary {{ k9s_version }}
  unarchive:
    src: "https://github.com/derailed/k9s/releases/download/{{ k9s_version }}/k9s_Linux_{{ download_arch }}.tar.gz"
    remote_src: yes
    dest: /usr/local/bin
    mode: "0755"
    owner: root
    creates: /usr/local/bin/k9s
  become: yes

- name: Download helm binary {{ helm_version }}
  unarchive:
    src: "https://get.helm.sh/helm-{{ helm_version }}-linux-{{ download_arch }}.tar.gz"
    remote_src: yes
    dest: /tmp
    creates: /tmp/linux-{{ download_arch }}/helm

- name: Install helm binary
  shell:
    cmd: |
      set -e
      cp /tmp/linux-{{ download_arch }}/helm /usr/local/bin/.
    creates: /usr/local/bin/helm
  become: yes

- name: Download flux binary {{ flux_version }}
  unarchive:
    src: "https://github.com/fluxcd/flux2/releases/download/v{{ flux_version }}/flux_{{ flux_version }}_linux_{{ download_arch }}.tar.gz"
    remote_src: yes
    dest: /tmp
    creates: /tmp/flux

- name: Install flux binary
  shell:
    cmd: |
      set -e
      cp /tmp/flux /usr/local/bin/.
    creates: /usr/local/bin/flux
  become: yes
