- name: Check if k3s service is configured
  stat:
    path: "/etc/systemd/system/k3s.service"
  register: master_svc

- name: Uninstall k3s master 
  command: >-
    /usr/local/bin/k3s-uninstall.sh
  when: master_svc.stat.exists

